# Generated by Django 3.2 on 2021-04-26 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('woo_id', models.IntegerField()),
                ('date_created', models.DateTimeField()),
                ('date_modified', models.DateTimeField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('billing_first_name', models.CharField(max_length=100)),
                ('billing_last_name', models.CharField(max_length=100)),
                ('billing_address', models.TextField(max_length=1000)),
                ('billing_city', models.CharField(max_length=100)),
                ('billing_state', models.CharField(max_length=100)),
                ('billing_post_code', models.CharField(blank=True, max_length=100, null=True)),
                ('billing_country', models.CharField(max_length=100)),
                ('billing_email', models.CharField(blank=True, max_length=100, null=True)),
                ('billing_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('woo_id', models.IntegerField()),
                ('date_created', models.DateTimeField()),
                ('date_modified', models.DateTimeField()),
                ('total', models.IntegerField()),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('date_paid', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('on-hold', 'On-Hold'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('failed', 'Failed'), ('trash', 'Trash')], max_length=100)),
                ('order_woo_number', models.CharField(blank=True, max_length=100, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='woosync.customer')),
            ],
        ),
    ]
