# Generated by Django 3.2 on 2021-04-27 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('woosync', '0004_auto_20210427_0617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='billing_address',
            new_name='billing_address_1',
        ),
    ]
