# Generated by Django 3.2 on 2021-04-27 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('woosync', '0005_rename_billing_address_customer_billing_address_1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='billing_post_code',
            new_name='billing_postcode',
        ),
    ]
