# Generated by Django 3.2 on 2021-08-03 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woosync', '0007_alter_customer_customer_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('percent', 'percent'), ('fixed_cart', 'fixed_cart')], max_length=100)),
                ('discount', models.IntegerField()),
                ('max_discount', models.IntegerField()),
                ('number_of_usage', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='mean_month_bought',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='number_of_failed_orders',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='number_of_successful_orders',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='total_bought',
            field=models.IntegerField(default=0),
        ),
    ]
